from django.conf.urls import patterns, url
from main.views import (
    IndexView,
    ProfileView,
    LibraryListView,
    LibraryCreate,
    LibraryDetailView,
    BookDetailView,
    BookCreate,
    BookDelete,
    NotificationListView,
    RegisterView,
    LogoutView,
    LoginView,
    BookUpdate,
    LoginRequiredView)

urlpatterns = patterns('',
                       url(r'^$', IndexView.as_view(), name='index'),
                       url(r'^profile/$', ProfileView.as_view(),
                           name='profile'),
                       url(r'^register/$', RegisterView.as_view(),
                           name='register'),
                       url(r'^login/$', LoginView.as_view(), name='login'),
                       url(r'^logout/$', LogoutView.as_view(), name='logout'),
                       url(r'^library/list/$',
                           LibraryListView.as_view(), name='library-list'),
                       url(r'^library/new/$',
                           LibraryCreate.as_view(), name='library-new'),
                       url(r'^library/(?P<pk>\d+)/$',
                           LibraryDetailView.as_view(),
                           name='library-detail'),
                       url(r'^book/(?P<slug>[-\w]+)/$',
                           BookDetailView.as_view(),
                           name='book-detail'),
                       url(r'^library/(?P<pk>\d+)/new/$',
                           BookCreate.as_view(),
                           name='book-new'),
                       url(r'^book/(?P<slug>[-\w]+)/delete/$',
                           BookDelete.as_view(),
                           name='book-delete'),
                       url(r'^books/edit/$',
                           BookUpdate.as_view(), name='edit-books'),
                       url(r'^notification/$',
                           NotificationListView.as_view(),
                           name='notification'),
                       url(r'^login_required/$',
                           LoginRequiredView.as_view(), name='login'),


                       )
